### ISSUE TITLE
How to use this info.

### ISSUE THREAD

**Issue by Savvytar** [Karmesinrot/Anifiltrs#40]
Im new new to github and i wanna know how to use this information to make a website.

**Comment by lolamtisch** [comment]
This is a ublock filter list. Has nothing to with websites.

With "github pages" you can host your website for free, as long you dont want a custom domain. But they only allow static websites with html, css and js. 

Github is only a place to save your code. It is public it makes it easy to work with multiple people on one project.

I would recommend you start learing html and css and build your website. When you are done upload it to github and enable github pages so that everyone can see it.

Good place to start is probably W3 Schools.

https://www.w3schools.com/
